/**
 * Copyright (c) 2014 Robert R. Russell 
 */
package com.rrbrussell.enigma_demonstration;

/**
 * Custom exception for violations of the RingSize constraint.
 * 
 * @author Robert R. Russell
 * @author robert@rrbrussell.com
 *
 */
public class RingSizeException extends IllegalArgumentException {

	/**
	 * Generated by Eclipse.
	 */
	private static final long serialVersionUID = 2433477433198639395L;

	/**
	 * This exception may be thrown by everything that deals with the
	 * Rotor.Ringsize constraint.
	 */
	public RingSizeException() {
		super("Argument must be between 0 and Rotor.RingSize - 1.");
	}
}